image: frekele/ant:1.10.1-jdk8

stages:
    - build
    - test

build:
    stage: build
    script: 
        - cd CovidTrackingDemo
        - ant compile

test:
    stage: test
    script: 
        - cd CovidTrackingDemo
        - ant runtest
