image: java:latest

stages:
    - build
    - test

build:
    stage: build
    script: 
        - cd CovidTrackingDemo
        - /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -cp .:lib/junit-4.10.jar src/covidtrackingdemo/Controller/HealthOrganization/LoginController.java src/covidtrackingdemo/Controller/HealthOrganization/LoginControllerTest.java test/TestRunner.java src/covidtrackingdemo/Entity/User.java
    artifacts:
        paths:
            - bin/TestRunner.class
            - bin/covidtrackingdemo/Controller/HealthOrganization/LoginController.class
            - bin/covidtrackingdemo/Controller/HealthOrganization/LoginControllerTest.class
            - bin/covidtrackingdemo/Entity/User.java

test:
    stage: test
    script: 
        - cd CovidTrackingDemo
        - /usr/lib/jvm/java-8-openjdk-amd64/bin/java -cp .:lib/junit-4.10.jar test/TestRunner
