image: docker:latest

services:
    - docker:dind

before_script:
    - docker run --rm -i ubuntu bash
    - apk update 
    - apk add apache-ant
    - apk add openjdk8

stages:
    - build
    - test
    
build:
    stage: build
    script:
        - cd CovidTrackingDemo 
        - ant compile

test:
    stage: test
    script: 
        - cd CovidTrackingDemo
        - ant runtest
