image: docker:latest

services:
    - docker:dind

before_script:
    - docker run -it ubuntu
    - apt-get update 
    - apt-get install ant
    
build:
    stage: build
    script:
        - ant -version
