image: docker:latest

services:
    - docker:dind

before_script:
    - docker run --rm -i ubuntu bash
    - apk update 
    - apk add apache-ant
    - apk add openjdk8

stages:
    - build
    - test
    
build:
    stage: build
    script:
        - cd CovidTrackingDemo 
        - ant compile
    artifacts:
        paths:
            - CovidTrackingDemo/bin/covidtrackingdemo/Controller/HealthOrganization/LoginController.class
            - CovidTrackingDemo/bin/covidtrackingdemo/Controller/HealthOrganization/LoginControllerTest.class
            - CovidTrackingDemo/bin/covidtrackingdemo/Entity/User.class
            - CovidTrackingDemo/bin/covidtrackingdemo/UserProfiles.class
            - CovidTrackingDemo/bin/TestRunner.class
            - CovidTrackingDemo/dataset/UserProfiles.csv

test:
    stage: test
    script: 
        - cd CovidTrackingDemo
        - ant runtest
