image: openjdk:14

before_script:
  - ant install

stages:
    - build
    - test

build:
    stage: build
    script: 
        - cd CovidTrackingDemo
        - ant compile

test:
    stage: test
    script: 
        - cd CovidTrackingDemo
        - ant runtest
