image: docker:latest

services:
    - docker:dind

before_script:
    - docker run --rm -i ubuntu bash
    - apk update 
    - apk add apache-ant
    
build:
    stage: build
    script:
        - ant runtest
