image: frekele/java:jdk8

stages:
    - build
    - test

build:
    stage: build
    script: 
        - cd CovidTrackingDemo
        - ant compile

test:
    stage: test
    script: 
        - cd CovidTrackingDemo
        - java -cp lib/junit-4.10.jar bin/TestRunner
