image: docker:latest

services:
    - docker:dind

before_script:
    - docker run ubuntu
    - docker apt-get update 
    - docker apt-get install ant
    
build:
    stage: build
    script:
        - docker ant -version
